---
############################################################
############################################################
## Initial AI Generation Metadata and FAQs for all Files ##
############################################################
############################################################

name: Initial AI Generation

######################################################
# Start the job on an initial AI metadata generaton #
######################################################

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Target branch to send PR to (e.g., main, stage, etc)"
        type: string
        required: false
        default: "main"
      folder_path:
        description: "Folder path to read files from (defaults to src/pages)"
        type: string
        required: false
        default: "src/pages"
jobs:
  ai-metadata-update:
    name: AI Metadata Update on Deployment
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/ai-deploy-metadata.yml@main
    with:
      FILE_NAME: "all_pages_content.txt"
      TARGET_BRANCH: ${{ inputs.target_branch }}
      FOLDER_PATH: ${{ inputs.folder_path }}
    secrets:
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}