---
###################################
###################################
## Nightly Refresh AI generation ##
###################################
###################################

name: Nightly AI Metadata Refresh

######################################################
# Start the job on a refresh for AI metadata generaton #
######################################################

on:
  # schedule:
  #   - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      baseSha:
        description: "Use base SHA commit to compare changes from (empty string defaults to last commit before HEAD)"
        type: string
        required: false
        default: ""
      target_branch:
        description: "Target branch to send PR to (e.g., main, stage, etc)"
        type: string
        required: false
        default: "main"
      folder_path:
        description: "Folder path to read files from (defaults to src/pages)"
        type: string
        required: false
        default: "src/pages"

jobs:
  ai-metadata-update:
    name: AI Metadata Update with Changed Files
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/ai-metadata-changed-files.yml@main
    with:
      baseSha: ${{ inputs.baseSha }}
      TARGET_BRANCH: ${{ inputs.target_branch }}
      FILE_NAME: "changed_content.txt"
      FOLDER_PATH: ${{ inputs.folder_path }}
    secrets:
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}