---
##############################################
##############################################
## Pull Request with AI Metadata Generation ##
##############################################
##############################################

name: AI Metadata Pull Request

######################################################
# Start the job on a pull request to the specified branch #
######################################################

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/pages/**'

###############
# Set the Job #
###############
jobs:
  call_reusable_workflow:
    name: Generate AI Metadata
    # Skip if PR title starts with "[AI PR] Metadata Update" or branch name starts with "ai-metadata"
    if: >-
      !startsWith(github.event.pull_request.title, '[AI PR] Metadata Update') ||
      !startsWith(github.event.pull_request.head.ref, 'ai-metadata')
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/ai-pr-request-metadata.yml@main
    with:
      PR_ID: ${{ github.event.pull_request.number }}
      FILE_NAME: "pr_content.txt"
    secrets:
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}