---
name: Production Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: "Select environment to deploy to"
        type: choice
        required: true
        default: "prod"
        options:
          - "prod"
          - "stage & prod"
      baseSha:
        description: "Use base SHA commit to deploy from (empty string defaults to last commit before HEAD)"
        type: string
        required: false
        default: ""
      deployAll:
        description: "Force deploy all files"
        type: boolean
        default: false
jobs:
  deployment:
    name: Deployment
    uses: AdobeDocs/adp-devsite-workflow/.github/workflows/deploy.yml@main
    secrets:
      AIO_AZURE_DEV_PRIVATE_CONNECTION_STRING: ${{ secrets.AIO_AZURE_DEV_PRIVATE_CONNECTION_STRING }}
      AIO_AZURE_PROD_PRIVATE_CONNECTION_STRING: ${{ secrets.AIO_AZURE_PROD_PRIVATE_CONNECTION_STRING }}
      AIO_FASTLY_TOKEN: ${{ secrets.AIO_FASTLY_TOKEN }}
      AIO_FASTLY_PROD_URL: ${{ secrets.AIO_FASTLY_PROD_URL }}
      AIO_FASTLY_DEV_URL: ${{ secrets.AIO_FASTLY_DEV_URL }}
    with:
      env: ${{ inputs.env || 'prod' }}
      baseSha: ${{ inputs.baseSha || '' }}
      deployAll: ${{ inputs.deployAll || false }}